### ISSUE TITLE
偶尔会有已停止报错   看起来是 core crash了

### ISSUE THREAD

**Issue by foxundermoon** [mellow-io/mellow#118]
### 使用操作系统类型以及版本

macOS 1.14.6 

### 使用 Mellow 版本
0.1.11

### 问题描述

偶尔提示弹窗错误

### 相关配置

```config
[Endpoint]
Proxy-1, vmess1, vmess1://75da2e14-4d08-480b-b3cb-0079a0c51275@example.com:443/path?network=ws&tls=true&ws.host=example.com
Direct, builtin, freedom, domainStrategy=UseIP
Dns-Out, builtin, dns
Pi, builtin, socks, address=192.168.1.168, port=11080

[RoutingRule]
DOMAIN-KEYWORD, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
FINAL, Pi

[Dns]
hijack = Dns-Out

[DnsServer]
localhost
8.8.8.8
```

### 相关日志

```log

[2020-01-30 16:45:46.110] [info] Retrying to find the TUN interface.
[2020-01-30 16:45:46.111] [info] The TUN interface before configuring routes:
[2020-01-30 16:45:46.111] [info] { address: '10.255.0.2', interface: 'utun233' }
[2020-01-30 16:45:46.145] [info] Set 10.255.0.1 as the default gateway.
[2020-01-30 16:45:46.147] [info] Core stopped, code 0 signal null



```

```log
goroutine 366281 [select]:
v2ray.com/core/transport/pipe.(*pipe).ReadMultiBufferTimeout(0xc004ce0a50, 0x11e1a300, 0x0, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/v2ray.com/core/transport/pipe/impl.go:139 +0x192
v2ray.com/core/transport/pipe.(*Reader).ReadMultiBufferTimeout(...)
	/ext-go/1/src/v2ray.com/core/transport/pipe/reader.go:26
v2ray.com/core/app/dispatcher.(*cachedReader).Cache(0xc001db75f0, 0xc000509eb8, 0x11e1a300)
	/ext-go/1/src/v2ray.com/core/app/dispatcher/default.go:39 +0x4a
v2ray.com/core/app/dispatcher.sniffer(0x4c04a00, 0xc003c05200, 0xc001db75f0, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/v2ray.com/core/app/dispatcher/default.go:267 +0x162
v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1(0xc000ba6600, 0x4c04a00, 0xc003c05200, 0xc004ce0a00, 0xc0000b00e0, 0x2, 0x2, 0x5f7ef01, 0xc000ba6580, 0xc003e0e5c0, ...)

[2020-01-30 07:28:58.146] [info] 	/ext-go/1/src/v2ray.com/core/app/dispatcher/default.go:226 +0xb2
created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
	/ext-go/1/src/v2ray.com/core/app/dispatcher/default.go:221 +0x30e

goroutine 366166 [select]:
io.(*pipe).Read(0xc0003e2f50, 0xc007442000, 0x8000, 0x8000, 0x0, 0x0, 0xc000638160)
	/usr/local/go/src/io/pipe.go:50 +0xe7
io.(*PipeReader).Read(...)
	/usr/local/go/src/io/pipe.go:127
github.com/eycorsican/go-tun2socks/core.(*tcpConn).Read(0xc002088000, 0xc007442000, 0x8000, 0x8000, 0x336, 0x0, 0x0)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/core/tcp_conn.go:204 +0x8b
github.com/eycorsican/go-tun2socks/proxy/v2ray.statsCopy(0x92722d0, 0xc004d91270, 0x92722f0, 0xc002088000, 0xc004c5c630, 0xc00654cc00, 0x40554b0, 0xc005666360, 0x92b1008)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/v2ray/tcp.go:44 +0x8f
github.com/eycorsican/go-tun2socks/proxy/v2ray.(*tcpHandler).relay.func2(0xc00016c600, 0xc004c5c630, 0x4c0fb20, 0xc004d91270, 0x5f7f670, 0xc002088000, 0xc0064f67e0, 0xc00171c660, 0xc00654cfc0)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/v2ray/tcp.go:88 +0x1e4
created by github.com/eycorsican/go-tun2socks/proxy/v2ray.(*tcpHandler).relay
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/v2ray/tcp.go:86 +0x13f

[2020-01-30 07:28:58.193] [info] Core stopped, code 2 signal null
[2020-01-30 07:28:58.194] [info] Core fails to startup, interrupt the starting procedure.
[2020-01-30 16:43:16.636] [info] Screen unlocked.
[2020-01-30 16:45:43.986] [info] Device resumed.
[2020-01-30 16:45:44.029] [info] Original gateway is 192.168.1.1
[2020-01-30 16:45:44.030] [info] Original send through 192.168.1.11 en0
[2020-01-30 16:45:44.040] [info] Core started.
[2020-01-30 16:45:44.067] [info] The default gateway before configuring routes:
[2020-01-30 16:45:44.068] [info] { gateway: '192.168.1.1', interface: 'en0' }
[2020-01-30 16:45:44.099] [info] 2020/01/30 16:45:44 Start session stater.

```

**Comment by foxundermoon** [comment]
频率还蛮高  一天会几次

`Failed to start the Core, see "/Users/fox/Library/Logs/Mellow/log.log" for more details.`

```log
goroutine 96455 [select]:
net.(*netFD).connect.func2(0x4c049c0, 0xc002469200, 0xc000689200, 0xc0020fc480, 0xc0020fc360)
	/usr/local/go/src/net/fd_unix.go:129 +0xba
created by net.(*netFD).connect
	/usr/local/go/src/net/fd_unix.go:128 +0x25a

goroutine 94595 [select, 1 minutes]:
v2ray.com/core/transport/pipe.(*pipe).ReadPacket(0xc0032f0050, 0x0, 0x0, 0x0, 0xc002329e00)
	/ext-go/1/src/v2ray.com/core/transport/pipe/impl.go:120 +0x107
v2ray.com/core/transport/pipe.(*Reader).ReadPacket(0xc0000e2f58, 0xc002329c40, 0xc00266b800, 0x0, 0x0)
	/ext-go/1/src/v2ray.com/core/transport/pipe/reader.go:21 +
[2020-02-01 11:34:12.348] [info] 0x2e
v2ray.com/core/common/buf.copyPacketInternal(0x4bf8400, 0xc0000e2f58, 0x4bf8140, 0xc002329d80, 0xc002329dc0, 0xc002ebbe01, 0xc002329da0)
	/ext-go/1/src/v2ray.com/core/common/buf/copy.go:100 +0x49
v2ray.com/core/common/buf.CopyPacket(0x4bf8400, 0xc0000e2f58, 0x4bf8140, 0xc002329d80, 0xc002ebbf70, 0x1, 0x1, 0x1, 0xc002c7eb00)
	/ext-go/1/src/v2ray.com/core/common/buf/copy.go:135 +0xa8
v2ray.com/core/proxy/socks.(*Client).Process.func5(0x0, 0x0)
	/ext-go/1/src/v2ray.com/core/proxy/socks/client.go:133 +0x1a4
v2ray.com/core/common/task.Run.func1(0xc0000ddc18, 0xc000be02a0, 0xc000be0180)
	/ext-go/1/src/v2ray.com/core/common/task/task.go:28 +0x2b
created by v2ray.com/core/common/task.Run
	/ext-go/1/src/v2ray.com/core/common/task/task.go:27 +0xd8

goroutine 95433 [IO wait]:
internal/poll.runtime_pollWait(0xe9835c8, 0x77, 0xc0011f7680)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc001d32718, 0x77, 0x4c04900, 0xc0027e67e0, 0xc001d32700)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitWrite(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:96
internal/poll.(*FD).WaitWrite(...)
	/usr/local/go/src/internal/poll/fd_unix.go:498
net.(*netFD).connect(0xc001d32700, 0x4c049c0, 0xc0027e67e0, 0x4bef7a0, 0xc001d060e0, 0x4bef7a0, 0xc002c56ea0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/fd_unix.go:152 +0x284
net.(*netFD).dial(0xc001d32700, 0x4c049c0, 0xc0027e67e0, 0x4c0b380, 0xc00081fec0, 0x4c0b380, 0xc00081ff20, 0x0, 
[2020-02-01 11:34:12.348] [info] 0xc00173b040, 0x412b9fe)
	/usr/local/go/src/net/sock_posix.go:149 +0xff
net.socket(0x4c049c0, 0xc0027e67e0, 0x4aa07dd, 0x3, 0x2, 0x1, 0x0, 0x0, 0x4c0b380, 0xc00081fec0, ...)
	/usr/local/go/src/net/sock_posix.go:70 +0x1ac
net.internetSocket(0x4c049c0, 0xc0027e67e0, 0x4aa07dd, 0x3, 0x4c0b380, 0xc00081fec0, 0x4c0b380, 0xc00081ff20, 0x1, 0x0, ...)
	/usr/local/go/src/net/ipsock_posix.go:141 +0x141
net.(*sysDialer).doDialTCP(0xc001d32680, 0x4c049c0, 0xc0027e67e0, 0xc00081fec0, 0xc00081ff20, 0x496d660, 0x58acfc0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:65 +0xc2
net.(*sysDialer).dialTCP(0xc001d32680, 0x4c049c0, 0xc0027e67e0, 0xc00081fec0, 0xc00081ff20, 0xc00173b280, 0x4100d7e, 0xbf855a4f6c1cd9c2)
	/usr/local/go/src/net/tcpsock_posix.go:61 +0xd7
net.(*sysDialer).dialSingle(0xc001d32680, 0x4c049c0, 0xc0027e67e0, 0x4bf6080, 0xc00081ff20, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:571 +0x34b
net.(*sysDialer).dialSerial(0xc001d32680, 0x4c049c0, 0xc0027e67e0, 0xc003b5bc50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go
[2020-02-01 11:34:12.348] [info] :539 +0x221
net.(*Dialer).DialContext(0xc00173b590, 0x4c04940, 0xc001d38480, 0x4aa07dd, 0x3, 0xc001d060c0, 0x15, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:417 +0x65e
v2ray.com/core/transport/internet.(*DefaultSystemDialer).Dial(0x5363c10, 0x4c04940, 0xc001d38480, 0x0, 0x0, 0x4c05f40, 0xc003156790, 0x200002941, 0x0, 0x304917360, ...)
	/ext-go/1/src/v2ray.com/core/transport/internet/system_dialer.go:129 +0x2af
v2ray.com/core/transport/internet.DialSystem(0x4c04940, 0xc001d38480, 0x4c05f40, 0xc003156790, 0x200002941, 0x0, 0x0, 0x0, 0x4bef240, 0xc00132e410)
	/ext-go/1/src/v2ray.com/core/transport/internet/dialer.go:84 +0xfa
v2ray.com/core/transport/internet/tcp.Dial(0x4c04940, 0xc001d38480, 0x4c05f40, 0xc003156790, 0x2000f2941, 0xc000491770, 0xc0000a5400, 0x5f13400, 0x0, 0xc00132e410)
	/ext-go/1/src/v2ray.com/core/transport/internet/tcp/dialer.go:18 +0x239
v2ray.com/core/transport/internet.Dial(0x4c04940, 0xc001d38480, 0x4c05f40, 0xc003156790, 0x200002941, 0xc000491770, 0x3b, 0xc003b60700, 0xc0042b04f0, 0xc003cf4658)
	/ext-go/1/src/v2ray.com/core/transport/internet/dialer.go:53 +0x284
v2ray.com/core/app/proxyman/outbound.(*Handler).Dial(0xc000491720, 0x4c04940, 0xc001d38480, 0x4c05f40, 0xc003156790, 0x203b62941, 0xc00173ba50, 0x4059f32, 0x404b3ec, 0x405c030)
	/ext-go/1/src/v2ray.com/core/app/proxyman/outbound/handler.go:158 +0xcc
v2ray.com/core/proxy/freedom.(*Handler).Process.func1(0x5f5e100, 0xc003b60700)
	/ext-go/1/src/v2ray.com/core/proxy/freedom/freedom.go:176 +0xaa
v2ray.com/core/common/retry.(*retryer).On(0xc00170c710, 0xc000ffcc80, 0x4beff40, 0xc00170c710)
	/ext-go/1/src/v2ray.com/core/common/retry/retry.go:29 +0xf7
v2ray.com/core/proxy/freedom.(*Handler).Process(0xc000043560, 0x4c04a00, 0xc001d9d260, 0xc003d7cd40, 0x4c01bc0, 0xc000491720, 0x0, 0x0)
	/ext-go/1/src/v2ray.com/core/proxy/freedom/freedom.go:162 +0x52c
v2ray.com/core/app/proxyman/outbound.(*Handler).Dispatch(0xc000491720, 0x4c04a00, 0xc001d9d260, 0xc003d7cd40)
	/ext-go/1/src/v2ray.com/core/app/proxyman/outbound/handler.go:106 +0x29b
v2ray.com/core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0002cbe00, 0x4c04a00, 0xc001d9d260, 0xc003d7cd40, 0x4c05f40, 0xc003156790, 0x2000b2941)
	/ext-go/1/src/v2ray.com/core/app/dispatcher/default.go:320 +0x1bc
v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1(0xc003d7cd40, 0x4c04a00, 0xc001d9d260, 0xc00211ee60, 0xc00000e260, 0x2, 0x2, 0x5fbe201, 0xc003d7ccc0, 0xc002630480, ...)
	/ext-go/1/src/v2ray.com/core/app/dispatcher/default.go:242 +0x138
created by v2ray.com/core/app/dispatcher.(*DefaultDispatcher).Dispatch
	/ext-go/1/src/v2ray.com/core/app/dispatcher/default.go:221 +0x30e

goroutine 96560 [runnable]:
github.com/eycorsican/go-tun2socks/core.(*tcpConn).Read(0xc004454f80, 0xc00148a000, 0x8000, 0x8000, 0x4
[2020-02-01 11:34:12.348] [info] , 0xc000f087b0, 0xc00141f980)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/core/tcp_conn.go:191 +0x19a
github.com/eycorsican/go-tun2socks/proxy/v2ray.statsCopy(0x9267840, 0xc0036d78b0, 0x9267860, 0xc004454f80, 0xc0019e2b40, 0xc001812600, 0x40554b0, 0xc001812600, 0xc000f08790)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/v2ray/tcp.go:44 +0x8f
github.com/eycorsican/go-tun2socks/proxy/v2ray.(*tcpHandler).relay.func2(0xc00060c180, 0xc0019e2b40, 0x4c0fb20, 0xc0036d78b0, 0x5fbe668, 0xc004454f80, 0xc004565278, 0xc0032c0930, 0xc00381bd10)
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/v2ray/tcp.go:88 +0x1e4
created by github.com/eycorsican/go-tun2socks/proxy/v2ray.(*tcpHandler).relay
	/ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/v2ray/tcp.go:86 +0x13f

[2020-02-01 11:34:12.359] [info] Core stopped, code 2 signal null
[2020-02-01 11:34:12.359] [info] Core fails to startup, interrupt the starting procedure.
[2020-02-01 13:24:09.582] [info] Screen unlocked.

```

**Comment by eycorsican** [comment]
日志需要刚出错后开头那部分
