### ISSUE TITLE
Failed to start the Core

### ISSUE THREAD

**Issue by guobosheng** [mellow-io/mellow#151]
[2020-03-07 21:35:28.343] [info] Created config folder /Users/username/Library/Application Support/Mellow/config
[2020-03-07 21:35:28.790] [info] Mellow (0.1.14) started.
[2020-03-07 21:37:12.901] [info] Shutting down the core.
[2020-03-07 21:37:12.922] [info] Core downed.
[2020-03-07 21:40:26.016] [info] Mellow (0.1.14) started.
[2020-03-07 21:40:54.276] [info] Checking helper files.
[2020-03-07 21:40:54.295] [info] Error: Command failed: "/Library/Application Support/Mellow/md5sum" "/Applications/Mellow.app/Contents/Resources/src/helper/geo.mmdb"
/bin/sh: /Library/Application Support/Mellow/md5sum: No such file or directory

    at checkExecSyncError (child_process.js:634:11)
    at execSync (child_process.js:670:15)
    at electron/js2c/asar.js:696:23
    at checkHelper (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:344:21)
    at up (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:730:14)
    at click (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:997:9)
    at MenuItem.click (electron/js2c/browser_init.js:1501:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1762:13)
[2020-03-07 21:40:54.296] [info] Installing helper.
[2020-03-07 21:40:54.297] [info] Executing: "/Applications/Mellow.app/Contents/Resources/src/helper/install_helper" "/Applications/Mellow.app/Contents/Resources/src/helper" "/Library/Application Support/Mellow"
[2020-03-07 21:41:03.096] [info] Helper installed.
[2020-03-07 21:41:03.115] [info] Original gateway is 192.168.0.1
[2020-03-07 21:41:03.118] [info] Original send through 192.168.0.2 en0
[2020-03-07 21:41:03.130] [info] Set system proxy with command: "/Applications/Mellow.app/Contents/Resources/src/helper/configure_proxy" "on" 2885 2886
[2020-03-07 21:41:05.050] [info] Core started.
[2020-03-07 21:41:05.069] [info] The default gateway before configuring routes:
[2020-03-07 21:41:05.070] [info] { gateway: '192.168.0.1', interface: 'en0' }
[2020-03-07 21:41:05.073] [info] Core errored.
[2020-03-07 21:41:05.077] [info] Error: spawn /Library/Application Support/Mellow/core EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2020-03-07 21:41:20.902] [info] Core stopped, code -13 signal null
[2020-03-07 21:41:20.903] [info] Core fails to startup, interrupt the starting procedure.
[2020-03-07 21:41:23.787] [info] Retrying to find the TUN interface.
[2020-03-07 21:41:25.800] [info] Retrying to find the TUN interface.
[2020-03-07 21:41:26.025] [info] Original gateway is 192.168.0.1
[2020-03-07 21:41:26.026] [info] Original send through 192.168.0.2 en0
[2020-03-07 21:41:26.030] [info] Set system proxy with command: "/Applications/Mellow.app/Contents/Resources/src/helper/configure_proxy" "on" 2885 2886
[2020-03-07 21:41:27.230] [info] Core started.
[2020-03-07 21:41:27.249] [info] The default gateway before configuring routes:
[2020-03-07 21:41:27.250] [info] { gateway: '192.168.0.1', interface: 'en0' }
[2020-03-07 21:41:27.257] [info] Core errored.
[2020-03-07 21:41:27.260] [info] Error: spawn /Library/Application Support/Mellow/core EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2020-03-07 21:41:29.642] [info] Core stopped, code -13 signal null
[2020-03-07 21:41:29.643] [info] Core fails to startup, interrupt the starting procedure.
[2020-03-07 21:41:30.442] [info] Retrying to find the TUN interface.
[2020-03-07 21:41:30.443] [info] Retrying to find the TUN interface.
[2020-03-07 21:41:32.380] [info] Shutting down the core.
[2020-03-07 21:41:32.398] [info] Core downed.

**Comment by Parahexen** [comment]
The core file is copied into **/Library/Application Support/Mellow**, and its permission misses execution privilege.
```
% ls -l /Library/Application\ Support/Mellow/
-rwSr-Sr-x  1 root  admin  22509876 Mar  8 02:06 core
-rw-r--r--  1 root  admin   4033189 Mar  8 02:06 geo.mmdb
-rw-r--r--  1 root  admin    754478 Mar  8 02:06 geosite.dat
-rwsr-sr-x  1 root  admin       127 Mar  8 02:06 md5sum
-rwsr-sr-x  1 root  admin     33584 Mar  8 02:06 route
%
```
Temp fix: `sudo chmod +x /Library/Application\ Support/Mellow/core`

**Comment by testermania** [comment]
win 1909 same it seems open in the task manager, but the program does not open.

**Comment by Eintler** [comment]
the same issue

**Comment by testermania** [comment]
> > Mellow (0.1.14) win 1909 same it seems open in the task manager, but the program does not open.
> 
> v0.1.15 is same.
> 
> ```
> [2020-03-07 23:55:12.788] [info] 2020/03/07 23:55:12 [Warning] v2ray.com/core: V2Ray started
> 
> [2020-03-07 23:55:14.789] [info] Retrying to find the TUN interface.
> [2020-03-07 23:55:14.791] [info] The TUN interface before configuring routes:
> [2020-03-07 23:55:14.791] [info] { address: '10.255.0.2', interface: 'mellow-tap0' }
> [2020-03-07 23:55:16.007] [info] Set 10.255.0.1 as the default gateway.
> [2020-03-07 23:56:10.708] [info] Shutting down the core.
> [2020-03-07 23:56:10.840] [info] Restore 192.168.1.1 as the default gateway.
> [2020-03-07 23:56:10.842] [info] Core downed.
> [2020-03-07 23:56:10.846] [info] Core stopped, code 0 signal null
> [2020-03-07 23:56:12.126] [info] Shutting down the core.
> [2020-03-07 23:56:12.247] [info] Core downed.
> [2020-03-08 12:57:27.499] [info] Mellow (0.1.15) started.
> ```

0.1.16 same

**Comment by testermania** [comment]
why closed still failed start core.

**Comment by eycorsican** [comment]
> why closed still failed start core.

Obviously you're encountering a different issue

**Comment by testermania** [comment]
I do not think so, why 0.1.13 working? I don't use setup.exe I extract the archive with uniextract. Could it be due to this?

**Comment by eycorsican** [comment]
> I do not think so, why 0.1.13 working? I don't use setup.exe I extract the archive. Could it be due to this?

The author of this issue uses macOS, it's an OS related issue.

I never try extracting mellow directly on windows, and I don't have a windows at hand.
