### ISSUE TITLE
Big Sur compatibility issues

### ISSUE THREAD

**Issue by lipeng21cn** [mellow-io/mellow#306]
### 使用操作系统类型以及版本

MAC OS 11.0.1 with M1 chip

### 使用 Mellow 版本

v0.1.22

### 问题描述

无法成功的建立vmess连接

### 问题复现步骤

1、确认相关配置文件在x86的MAC中可以成功连接
2、完整复制相关配置到M1的MACOS上（MAC MINI 2020 with m1 chip)

### 相关配置

[Endpoint]
Direct, builtin, freedom, domainStrategy=UseIP
Reject, builtin, blackhole
Dns-Out, builtin, dns
;#####################################################################################################
CONNECT_RU-REDRT, vmess1, vmess1://2c9a9cf3-9a9d-43b0-ac14-6cb6dd8e60d6@www.12345.com:21443/my-v2ray?network=ws&ws.host=us.edge.12.cn&tls=true&tls.allowinsecure=true
;#####################################################################################################

[Routing]
domainStrategy = IPIfNonMatch

[RoutingRule]
DOMAIN-KEYWORD, geosite:category-ads-all, Reject
DOMAIN-SUFFIX, geosite:cn, Direct
GEOIP, cn, Direct
GEOIP, private, Direct
;PORT, 5900, Direct
;PORT, 5901, Direct
;PORT, 5902, Direct
;PORT, 5903, Direct
;PORT, 5904, Direct
IP-CIDR, 10.0.0.0/8, Direct
IP-CIDR, 172.16.0.0/12, Direct
IP-CIDR, 192.168.0.0/16, Direct
IP-CIDR, 114.114.114.114/32, Direct
IP-CIDR, 114.114.115.115/32, Direct
IP-CIDR, 223.5.5.5/32, Direct
IP-CIDR, 223.6.6.6/32, Direct
IP-CIDR, 180.76.76.76/32, Direct
PROCESS-NAME, vncviewer.exe, Direct
PROCESS-NAME, v2rayN.exe, Direct
PROCESS-NAME, openvpn-gui.exe, Direct
PROCESS-NAME, openvpn.exe, Direct
IP-CIDR, 8.8.8.8/32, CONNECT_RU-REDRT
IP-CIDR, 8.8.4.4/32, CONNECT_RU-REDRT
FINAL, CONNECT_RU-REDRT

[Dns]
hijack = Dns-Out
;clientIp = 223.5.5.5

[DnsServer]
223.5.5.5, 53, DOMSDNS
8.8.8.8, 53, INTLDNS

;[DnsHost]
;domain = ip
;doubleclick.net = 127.0.0.1

[DnsRule]
DOMAIN-KEYWORD, geosite:cn, DOMSDNS
DOMAIN-KEYWORD, geosite:geolocation-!cn, INTLDNS

### 相关日志、截图

1, 当点击CONNECT后提示： 
ERROR   Failed to configure routes, see "/Users/peng/Library/Logs/Mellow/log.log" for more details.

2, LOGS如下：
[2020-11-29 00:02:21.351] [info] Mellow (0.1.22) started.
[2020-11-29 00:03:06.653] [info] Checking helper files.
[2020-11-29 00:03:07.280] [info] Original gateway is 192.168.1.1
[2020-11-29 00:03:07.281] [info] Original send through 192.168.1.64 en1
[2020-11-29 00:03:07.286] [info] Set system proxy with command: "/Applications/Mellow.app/Contents/Resources/src/helper/configure_proxy" "on" 2885 2886
[2020-11-29 00:03:07.628] [info] Core started.
[2020-11-29 00:03:07.639] [info] The default gateway before configuring routes:
[2020-11-29 00:03:07.639] [info] { gateway: '192.168.1.1', interface: 'en1' }
[2020-11-29 00:03:07.680] [info] 2020/11/29 00:03:07 Relay ICMP packets.

[2020-11-29 00:03:07.727] [info] 2020/11/29 00:03:07 Start session stater.

[2020-11-29 00:03:07.728] [info] 2020/11/29 00:03:07 Running tun2socks

[2020-11-29 00:03:07.728] [info] 2020/11/29 00:03:07 [Warning] v2ray.com/core: V2Ray started

[2020-11-29 00:03:09.649] [info] Retrying to find the TUN interface.
[2020-11-29 00:03:09.651] [info] The TUN interface before configuring routes:
[2020-11-29 00:03:09.652] [info] { address: '10.255.0.2', interface: 'utun233' }
[2020-11-29 00:03:09.694] [info] Error: Command failed: "/Library/Application Support/Mellow/route" delete default
    at checkExecSyncError (child_process.js:634:11)
    at execSync (child_process.js:670:15)
    at electron/js2c/asar.js:727:23
    at configRoute (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:703:9)
[2020-11-29 00:03:09.695] [info] Error: Command failed: "/Library/Application Support/Mellow/route" delete default
    at checkExecSyncError (child_process.js:634:11)
    at execSync (child_process.js:670:15)
    at electron/js2c/asar.js:727:23
    at configRoute (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:703:9)
[2020-11-29 00:03:40.385] [info] Original gateway is 192.168.1.1
[2020-11-29 00:03:40.385] [info] Original send through 192.168.1.64 en1
[2020-11-29 00:03:40.386] [info] Set system proxy with command: "/Applications/Mellow.app/Contents/Resources/src/helper/configure_proxy" "off" 2885 2886
[2020-11-29 00:03:40.699] [info] Set system proxy with command: "/Applications/Mellow.app/Contents/Resources/src/helper/configure_proxy" "on" 2885 2886
[2020-11-29 00:03:41.020] [info] Core started.
[2020-11-29 00:03:41.030] [info] The default gateway before configuring routes:
[2020-11-29 00:03:41.031] [info] { gateway: '192.168.1.1', interface: 'en1' }
[2020-11-29 00:03:41.031] [info] Core stopped, code 0 signal null
[2020-11-29 00:03:41.046] [info] 2020/11/29 00:03:41 Relay ICMP packets.

[2020-11-29 00:03:41.087] [info] 2020/11/29 00:03:41 Start session stater.

[2020-11-29 00:03:41.088] [info] 2020/11/29 00:03:41 Running tun2socks

[2020-11-29 00:03:41.088] [info] 2020/11/29 00:03:41 [Warning] v2ray.com/core: V2Ray started

[2020-11-29 00:03:42.860] [info] Shutting down the core.
[2020-11-29 00:03:42.894] [info] Set system proxy with command: "/Applications/Mellow.app/Contents/Resources/src/helper/configure_proxy" "off" 2885 2886

**Comment by fufu7755** [comment]
相同的问题

**Comment by zonozhang** [comment]
同样 M1 ，Failed to configure routes
