### ISSUE TITLE
无法在M1芯片的mac上开启透明代理

### ISSUE THREAD

**Issue by Atry** [mellow-io/mellow#315]
### 使用操作系统类型以及版本
macOS 11.1 (Apple M1)

### 使用 Mellow 版本
v0.1.22

### 问题描述

<img width="328" alt="截屏2021-01-21 20 48 49" src="https://user-images.githubusercontent.com/601530/105447919-1378d580-5c2a-11eb-9083-54e9a5f61737.png">
虽然会报错，但代理服务器可以使用。问题是直连时不会启用代理

### 问题复现步骤
打开 Mellow，连接任意配置

### 相关配置
任意配置

### 相关日志、截图

```
[2021-01-21 20:42:43.666] [info] Error: Command failed: "/Library/Application Support/Mellow/route" delete default
    at checkExecSyncError (child_process.js:634:11)
    at execSync (child_process.js:670:15)
    at electron/js2c/asar.js:727:23
    at configRoute (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:703:9)
[2021-01-21 20:43:41.037] [info] Original gateway is 192.168.1.1
[2021-01-21 20:43:41.038] [info] Original send through 192.168.1.19 en0
[2021-01-21 20:43:41.042] [info] Set system proxy with command: "/Applications/Mellow.app/Contents/Resources/src/helper/configure_proxy" "off" 2885 2886
[2021-01-21 20:43:41.617] [info] Core started.
[2021-01-21 20:43:41.629] [info] The default gateway before configuring routes:
[2021-01-21 20:43:41.630] [info] { gateway: '192.168.1.1', interface: 'en0' }
[2021-01-21 20:43:41.631] [info] Core stopped, code 0 signal null
```

**Comment by Atry** [comment]
作者跑路了。我把修改后的版本上传到我的分支了：https://github.com/Atry/mellow/releases/tag/v0.1.22-patch-1

**Comment by ihewro** [comment]
> 作者跑路了。我把修改后的版本上传到我的分支了：https://github.com/Atry/mellow/releases/tag/v0.1.22-patch-1

下载了这个版本 仍然是有问题的，稍后贴上日志
