### ISSUE TITLE
macOS上无法连接

### ISSUE THREAD

**Issue by Jimmy2Angel** [mellow-io/mellow#86]
环境：macOS Sierra + mellow v0.1.8
配置为提供的全局配置，日志信息如下
```
[2019-11-21 20:54:39.451] [info] Created config folder /Users/lollipop/Library/Application Support/Mellow/config
[2019-11-21 20:54:39.546] [info] Mellow (0.1.8) started.
[2019-11-21 20:57:50.199] [info] Checking helper files.
[2019-11-21 20:57:50.208] [info] Error: Command failed: "/Library/Application Support/Mellow/md5sum" "/Applications/Mellow.app/Contents/Resources/src/helper/geo.mmdb"
/bin/sh: /Library/Application Support/Mellow/md5sum: No such file or directory

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:665:15)
    at electron/js2c/asar.js:744:23
    at electron/js2c/asar.js:744:23
    at checkHelper (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:305:21)
    at up (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:632:14)
    at click (/Applications/Mellow.app/Contents/Resources/app.asar/src/main.js:899:9)
    at MenuItem.click (/Applications/Mellow.app/Contents/Resources/electron.asar/browser/api/menu-item.js:48:17)
    at Function.executeCommand (/Applications/Mellow.app/Contents/Resources/electron.asar/browser/api/menu.js:32:17)
[2019-11-21 20:57:50.209] [info] Installing helper.
[2019-11-21 20:57:50.209] [info] Executing: "/Applications/Mellow.app/Contents/Resources/src/helper/install_helper" "/Applications/Mellow.app/Contents/Resources/src/helper" "/Library/Application Support/Mellow"
[2019-11-21 20:57:57.351] [info] Helper installed.
[2019-11-21 20:57:57.359] [info] Original gateway is 192.168.1.1
[2019-11-21 20:57:58.364] [info] Retrying to find the original send through address.
[2019-11-21 20:57:59.370] [info] Retrying to find the original send through address.
[2019-11-21 20:58:00.372] [info] Retrying to find the original send through address.
[2019-11-21 20:58:01.376] [info] Retrying to find the original send through address.
[2019-11-21 20:58:02.380] [info] Retrying to find the original send through address.
[2019-11-21 20:58:02.381] [info] Can not find original send through.

```

**Comment by eycorsican** [comment]
连接前网络要正常，比如说要先连上个 WIFI

**Comment by Jimmy2Angel** [comment]
> 连接前网络要正常，比如说要先连上个 WIFI

网络是正常的，应用程序均正常使用

**Comment by eycorsican** [comment]
看起来是安装出错
